{
 "title": "financial",
 "description": "asd",
 "time": { "from": "2024-11-24T14:00:00.000Z", "to": "2024-11-24T18:00:00.000Z" },
 "panels": [
  {
   "title": "Top 10 Clients by Total Spend",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  client_id,\r\n  SUM(amount) AS total_spent\r\nFROM\r\n  transactions\r\nGROUP BY\r\n  client_id\r\nORDER BY\r\n  total_spent DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Total Transaction Amount Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('1 hour', date) AS time,\r\n  SUM(amount) AS total_amount\r\nFROM\r\n  transactions\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time;"
    }
   ]
  },
  {
   "title": "Geographical Distribution of Transactions",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  merchant_state,\r\n  COUNT(*) AS transactions_count\r\nFROM\r\n  transactions\r\nGROUP BY\r\n  merchant_state\r\nORDER BY\r\n  transactions_count DESC;"
    }
   ]
  },
  {
   "title": " Total Transactions Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('1 hour', date) AS time,\r\n  COUNT(*) AS total_transactions\r\nFROM\r\n  transactions\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time;"
    }
   ]
  },
  {
   "title": "Average Transaction Amount by Hour of Day",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time_bucket('1 hour', date) AS time,\r\n  SUM(amount) AS total_amount\r\nFROM\r\n  transactions\r\nGROUP BY\r\n  time\r\nORDER BY\r\n  time;"
    }
   ]
  },
  {
   "title": "Top 10 Merchants by Transaction Volume",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  merchant_id,\r\n  COUNT(*) AS transaction_count\r\nFROM\r\n  transactions\r\nGROUP BY\r\n  merchant_id\r\nORDER BY\r\n  transaction_count DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  month,\r\n  COUNT(*) AS transactions_count,\r\n  SUM(amount) AS total_amount\r\nFROM\r\n  transactions\r\nGROUP BY\r\n  month\r\nORDER BY\r\n  month;"
    }
   ]
  }
 ]
}